version: '3'

services:

  prometheus-server:
    build:
      context: prometheus-server/
    volumes:
    - prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      - prometheus

  node-exporter:
    build:
      context: node-exporter/
    #volumes:
    #  - node-exporter:/node-exporter
    ports:
      - "9100:9100"
    #networks:
    #  - prometheus
    network_mode: "host"
    pid: "host"
    volumes:
       - /proc:/host/proc
       - /sys:/host/sys
       - /:/rootfs

  alertmanager:
    build:
      context: alert-manager/
    volumes:
      - alertmanager:/alertmanager
    ports:
      - "9093:9093"
    networks:
      - prometheus

  blackbox:
    build:
      context: blackbox/
    ports:
      - "9115:9115"
    networks:
      - prometheus

# if you have move the docker path then just map your path to /var/lib/docker in the container. 

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9101:8080
    networks:
      - prometheus
    restart: always
    deploy:
      mode: global





  
networks:
  prometheus:
    driver: bridge

volumes: 
  prometheus:
  alertmanager:
