version: '3'

services:

  prometheus-server:
    build:
      context: prometheus-server/
    #volumes:
    #  - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9090:9090"
    networks:
      - prometheus

  node-exporter:
    build:
      context: node-exporter/
    #volumes:
    #  - node-exporter:/node-exporter
    ports:
      - "9100:9100"
    #networks:
    #  - prometheus
    network_mode: "host"
    pid: "host"
    volumes:
       - /proc:/host/proc
       - /sys:/host/sys
       - /:/rootfs

  alertmanager:
    build:
      context: alert-manager/
    volumes:
      - alertmanager:/alertmanager
    ports:
      - "9093:9093"
    networks:
      - prometheus

networks:
  prometheus:
    driver: bridge

volumes: 
  prometheus:
  alertmanager:
